#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# Prepare a CARLA town's HD map so the Autoware PCLA agent can drive there.
# Produces, for <TownXX>:
#   carla_map/<TownXX>/lanelet2_map.osm        (community Lanelet2 map, same frame as ours)
#   carla_map/<TownXX>/map_projector_info.yaml (town-generic projector)
#   carla_map/<TownXX>/pointcloud_map.pcd      (GENERATED by sweeping a LiDAR over the town)
#   external/zenoh_autoware_v2x/carla_maps/<TownXX>/map_info.json  (traffic-light table)
#
# Requires CARLA running (any map). This script stops the zenoh bridge so the pointcloud
# generator can drive synchronous mode itself, then loads <TownXX> and sweeps it.
# Run once per town, THEN:  TOWN=<TownXX> bash ~/start_stack.sh
#
# Usage:  bash prepare_town.sh Town02
# ---------------------------------------------------------------------------
set -e
TOWN="${1:?usage: prepare_town.sh <TownXX>   (CARLA must be running)}"
AWROOT="${AWROOT:-$HOME/autoware_carla_launch}"
KIT="$(cd "$(dirname "$0")" && pwd)"
PY="${PCLA_PY:-python}"   # python with the CARLA 0.9.16 client (activate the PCLA env)
OSM_BASE="https://raw.githubusercontent.com/hatem-darweesh/op_agent/ros2/autoware-contents/maps/vector_maps/lanelet2"
DST="$AWROOT/carla_map/$TOWN"
TL="$AWROOT/external/zenoh_autoware_v2x/carla_maps/$TOWN"
mkdir -p "$DST" "$TL"

if docker ps >/dev/null 2>&1; then DOCKER="docker"; else DOCKER="sudo docker"; fi

# 1) Lanelet2 map (community; same y-flip frame as our pcd + adapter).
if [ ! -f "$DST/lanelet2_map.osm" ]; then
    echo "[prepare_town] fetching $TOWN lanelet2 map..."
    curl -fsSL -o "$DST/lanelet2_map.osm" "$OSM_BASE/$TOWN.osm" || {
        echo "[prepare_town] ERROR: no community Lanelet2 map for $TOWN."
        echo "               For a custom/source-built town, generate one from its OpenDRIVE (see README)."
        rm -f "$DST/lanelet2_map.osm"; exit 1; }
fi

# 2) map projector (town-generic: TransverseMercator, origin 0,0,0).
cp "$AWROOT/carla_map/Town01/map_projector_info.yaml" "$DST/map_projector_info.yaml"

# 3) pointcloud map -- generated from the sim. Stop the bridge first so we own sync mode.
$DOCKER exec aw_bridge pkill -9 -f zenoh_carla_bridge >/dev/null 2>&1 || true
sleep 1
if [ ! -f "$DST/pointcloud_map.pcd" ]; then
    echo "[prepare_town] generating $TOWN pointcloud map (LiDAR sweep; a few minutes)..."
    "$PY" "$KIT/gen_pointcloud.py" --town "$TOWN" --out "$DST/pointcloud_map.pcd"
fi

# 4) traffic-light table from the Lanelet2 map.
echo "[prepare_town] generating $TOWN traffic-light table..."
"$PY" "$KIT/gen_map_info.py" --osm "$DST/lanelet2_map.osm" --out "$TL/map_info.json"

echo "[prepare_town] $TOWN ready.  Now:  TOWN=$TOWN bash ~/start_stack.sh"
